In [6]:
import numpy as np
import pickle

# Matricies

This notebook uses many images from the excellent [A Visual Intro to NumPy and Data Representation](https://jalammar.github.io/visual-numpy/) from [Jay Alammar](https://jalammar.github.io/).

In the first notebook ([vector.ipynb](https://github.com/ADGEfficiency/teaching-monolith/blob/master/numpy/1.vector.ipynb)) we dealt with vectors (one dimensional). 

Now we deal with **Matricies** - arrays with two dimensions.

$\textbf{A}_{2, 2} = \begin{bmatrix}A_{1, 1} & A_{1, 2} \\ A_{2, 1} & A_{2, 2}\end{bmatrix}$

- two dimensional
- uppercase, bold $\textbf{A}_{m, n}$
- $A_{1, 1}$ = first element
- area
- tabular data

## Reshaping

Now that we have multiple dimensions, we need to start considering shape.

We can see the shape using `.shape`

In [2]:
data = np.arange(16)

In [5]:
data2 = data.reshape(4,4)
data2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [4]:
data

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [7]:
data2[0, 0] = 999
data2

array([[999,   1,   2,   3],
       [  4,   5,   6,   7],
       [  8,   9,  10,  11],
       [ 12,  13,  14,  15]])

In [8]:
data

array([999,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15])

And the number of elements using `.size`

The **shape** of a matrix becomes more than just an indication of the length.  We can change the shape using reshape:

A very useful tool when reshaping is using `-1` - this is a free dimension that will be set to match the size of the data
- this is often set to the batch / number of samples dimension

In [9]:
data.reshape(2,-1)

array([[999,   1,   2,   3,   4,   5,   6,   7],
       [  8,   9,  10,  11,  12,  13,  14,  15]])

In [10]:
data.reshape(-1, 2)

array([[999,   1],
       [  2,   3],
       [  4,   5],
       [  6,   7],
       [  8,   9],
       [ 10,  11],
       [ 12,  13],
       [ 14,  15]])

We can use `.reshape` to flatten

In [11]:
data.reshape(-1)

array([999,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15])

In [16]:
data.resize((2,8))

In [17]:
data

array([[999,   1,   2,   3,   4,   5,   6,   7],
       [  8,   9,  10,  11,  12,  13,  14,  15]])

We can also use `.flatten`

In [20]:
data.flatten()

array([999,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15])

And finally `.ravel`

In [21]:
data

array([[999,   1,   2,   3,   4,   5,   6,   7],
       [  8,   9,  10,  11,  12,  13,  14,  15]])

In [24]:
x = data.ravel()

In [25]:
data

array([[999,   1,   2,   3,   4,   5,   6,   7],
       [  8,   9,  10,  11,  12,  13,  14,  15]])

Looking at the difference between ravel returning a view (not actual copy, just view of the original object)

`.flatten` always returns a copy - `.ravel` doesn't (if it can)

Closely related to a reshape is the **transpose**, which flips the array along the diagonal:

<img src="assets/trans.png" alt="" width="300"/>

In [27]:
data = np.reshape(np.arange(1,7), (3,2))
data

array([[1, 2],
       [3, 4],
       [5, 6]])

In [31]:
dataT = data.T
dataT

array([[1, 3, 5],
       [2, 4, 6]])

In [29]:
data

array([[1, 2],
       [3, 4],
       [5, 6]])

In [32]:
data[0, 0] = 999
data

array([[999,   2],
       [  3,   4],
       [  5,   6]])

In [33]:
dataT

array([[999,   3,   5],
       [  2,   4,   6]])

Reshape is (usually) computationally **cheap** - to understand why we need to know a little about how a `np.array` is laid out in memory

## The `np.array` in memory

- the data is stored in a single block
- the shape is stored as a tuple

Why is storing in a single block (known as a contiguous layout) a good thing?
- to access the next value an the array 
- we just move to the next memory address
- length = defined by the data type

> ... storing data in a contiguous block of memory ensures that the architecture of modern CPUs is used optimally, in terms of memory access patterns, CPU cache, and vectorized instructions - [iPython coobook](https://ipython-books.github.io/45-understanding-the-internals-of-numpy-to-avoid-unnecessary-array-copying/)

Changing the shape only means changing the tuple 
- the layout of the data in memory is not changed

The operations that will change the memory layout are ones that change the order of the data - for example a transpose:

In [34]:
data = np.arange(10000000).reshape(5, -1)
res = %timeit -qo data.reshape((1, -1))
'{:.8f} seconds'.format(res.average)

'0.00000023 seconds'

In [35]:
data = np.arange(10000000).reshape(5, -1)
res = %timeit -qo data.T.reshape((1, -1))
'{:.8f} seconds'.format(res.average)

'0.01911655 seconds'

## Two dimensional indexing

<img src="assets/idx2.png" alt="" width="500"/>

In [37]:
data = np.reshape(np.arange(1,7),(3,2))
data

array([[1, 2],
       [3, 4],
       [5, 6]])

We specify both dimensions using a familiar `[]` syntax

`:` = entire dimension

In [41]:
data[:,-1].reshape(3,1)

array([[2],
       [4],
       [6]])

`-1` = last element

### Two dimension aggregation

<img src="assets/agg-2d.png" alt="" width="900"/>

Now that we are working in two dimensions, we have more flexibility in how we aggregate
- we can specify the axis (i.e. the dimension) along which we aggregate

In [45]:
data = np.array([[1, 2], [5, 3], [4, 6]])

In [46]:
data.max(axis=0)

array([5, 6])

In [47]:
data.max(axis=1)

array([2, 5, 6])

By default `numpy` will remove the dimension you are aggregating over:

In [50]:
data

array([[1, 2],
       [5, 3],
       [4, 6]])

In [49]:
np.mean(data, axis=1)

array([1.5, 4. , 5. ])

You can choose to keep this dimension using a `keepdims` argument:

In [55]:
np.mean(data, axis=1, keepdims=True)

array([[1.5],
       [4. ],
       [5. ]])

## Practical

Aggregate by variance `np.var` 
- over the rows
- over the columns
- over all data

In [51]:
np.var(data, axis=1)

array([0.25, 1.  , 1.  ])

In [53]:
np.var(data, axis=0)

array([2.88888889, 2.88888889])

In [54]:
np.var(data)

2.9166666666666665

## Two dimensional broadcasting

The general rule with broadcasting - dimensions are compatible when
- they are equal
- or when one of them is 1

<img src="assets/broad-2d.png" alt="" width="500"/>

In [56]:
 data + np.ones

array([[1, 2],
       [5, 3],
       [4, 6]])

## Matrix arithmetic

Can make arrays from nested lists:

In [57]:
a = np.array(np.arange(1,5)).reshape(2,2)
a

array([[1, 2],
       [3, 4]])

We can add matricies of the same shape as expected:

<img src="assets/add-matrix.png" alt="" width="300"/>

In [59]:
ones = np.ones_like(a)
ones

array([[1, 1],
       [1, 1]])

In [60]:
a + ones

array([[2, 3],
       [4, 5]])

## Matrix multiplication

This kind of matrix multiplication will often **change the shape** of the array
- this is what happens in neural networks

<img src="assets/dot1.png" alt="" width="900"/>

This operation can be visualized:

<img src="assets/dot2.png" alt="" width="900"/>

In [63]:
data = np.array(np.arange(1,4))
powers_of_ten = np.array([10**x for x in range(6)]).reshape(3,2)
powers_of_ten

array([[     1,     10],
       [   100,   1000],
       [ 10000, 100000]])

This is done in numpy using either `np.dot()`:

In [64]:
np.dot(data, powers_of_ten)

array([ 30201, 302010])

In [65]:
data.dot(powers_of_ten)

array([ 30201, 302010])

In [67]:
data @ powers_of_ten

array([ 30201, 302010])

Or calling the `.dot()` method on the array itself:

## Making arrays from nested lists

## Making arrays from shape tuples

The argument to these functions is a tuple

### `zeros`, `ones`, `full`

In [70]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [71]:
np.full((3,4), 99)

array([[99, 99, 99, 99],
       [99, 99, 99, 99],
       [99, 99, 99, 99]])

### `zeros_like`, `ones_like`, `full_like`

Similar to counterparts above, except their shape is defined by another array:

In [72]:
parent = np.arange(0, 10).reshape(2,5)
parent

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [73]:
np.zeros_like(parent)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [74]:
np.ones_like(parent)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [76]:
np.full_like(parent, 99)

array([[99, 99, 99, 99, 99],
       [99, 99, 99, 99, 99]])

### `empty`

Similar to `zeros`, except the array is filled with garbage from RAM 
- this is a bit quicker than `zeros`

In [79]:
np.empty((5,2))

array([[4.63644493e-310, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000],
       [2.22809558e-312, 2.34394382e-056],
       [2.14331456e+184, 4.75972319e-090],
       [8.06860228e+169, 8.74261356e-313]])

### `eye`

Identity matrix :

In [84]:
np.eye(4,5,1)

array([[0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

The linear algebra verision of a 1

*** dot product times the identity matrix is like multiplying by 1

## Matrix Practice

1. Write a function (using numpy) to sort a diven array of shape 2 along the first axis (rows), second axis (column), and on a flattened array.

example: 

In [54]:
# Expected Output:
# Original array:
np.array([[10, 40],
          [30, 20]])
# Sort the array along the first axis:
np.array([[10, 20],
          [30, 40]])
# Sort the array along the last axis:
np.array([[10, 40],
          [20, 30]])
# Sort the flattened array:
np.array([10, 20, 30, 40])

array([10, 20, 30, 40])

In [86]:
orig = np.array([[10, 40],
          [30, 20]])
orig

array([[10, 40],
       [30, 20]])

In [88]:
np.sort(orig, axis=0)

array([[10, 20],
       [30, 40]])

In [90]:
np.sort(orig, axis=1)

array([[10, 40],
       [20, 30]])

In [91]:
np.sort(orig.flatten())

array([10, 20, 30, 40])

2. Write a function to get the indicies of the sorted elements of a given array

Expected Output:

Original array:


`[1023 5202 6230 1671 1682 5241 4532]`


Indices of the sorted elements of a given array:


`[0 3 4 6 1 5 2]`

In [120]:
data = [1023, 5202, 6230, 1671, 1682, 5241, 4532]
sorted_data = np.sort(data)
[data.index(x) for x in sorted_data]

[0, 3, 4, 6, 1, 5, 2]

3. Write a function to sort a specified number of elements from the beginning of a given array

Sample output:


Original array:


`[0.39536213 0.11779404 0.32612381 0.16327394 0.98837963 0.25510787 0.01398678 0.15188239 0.12057667 0.67278699]`


Sorted first 5 elements:

`[0.01398678 0.11779404 0.12057667 0.15188239 0.16327394 0.25510787 0.39536213 0.98837963 0.32612381 0.67278699]`

In [115]:
data = np.round(np.random.rand(10) * 10)
print(data)
n = 5
result = np.empty(data.size)
result[:n] = np.sort(data[:n])
result[n + 1 :] = data[n + 1 :]
print(result)

[2. 8. 6. 1. 0. 4. 8. 9. 7. 3.]
[0. 1. 2. 6. 8. 4. 8. 9. 7. 3.]


In [142]:
x = np.array([13, 14, 12, 11, 20, 99])
n = 2
print(x)
print(np.sort(x))
print(np.argsort(x))
print(np.argpartition(x,n))
print(x[np.argpartition(x,n)])
x

[13 14 12 11 20 99]
[11 12 13 14 20 99]
[3 2 0 1 4 5]
[3 2 0 1 4 5]
[11 12 13 14 20 99]


array([13, 14, 12, 11, 20, 99])

In [138]:
x.argmax()

5