In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import sys

In [8]:
v = np.array([0, 1, 3])
v

array([0, 1, 3])

In [5]:
np.strides?

Object `np.strides` not found.


In [10]:
v.strides?

Type:        tuple
String form: (8,)
Length:      1
Docstring:  
Built-in immutable sequence.

If no argument is given, the constructor returns an empty tuple.
If iterable is specified the tuple is initialized from iterable's items.

If the argument is a tuple, the return value is the same object.


In [12]:
x = np.reshape(np.arange(12), (4,3))
x

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [16]:
coord = 
x[coord]

/tmp/ipykernel_3879/609649815.py:2: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  x[coord]


array([1, 1])

In [33]:
n = 4
a = np.array(np.arange(n*n*3)).reshape(n,n,3)
print(a)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]

 [[24 25 26]
  [27 28 29]
  [30 31 32]
  [33 34 35]]

 [[36 37 38]
  [39 40 41]
  [42 43 44]
  [45 46 47]]]


In [34]:
print(a[...,:3])

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]

 [[24 25 26]
  [27 28 29]
  [30 31 32]
  [33 34 35]]

 [[36 37 38]
  [39 40 41]
  [42 43 44]
  [45 46 47]]]


In [13]:
image_size = (100, 500)  # Width, Height
image_counts = (3, 2) # Colums, Rows (corresponds with Width, Height)
picture_size = (image_counts[0] * image_size[0], image_counts[1] * image_size[1])
print(picture_size)

(300, 1000)


In [14]:
pos_x = np.linspace(0, picture_size[0], image_counts[0], endpoint=False)
print(list(pos_x))
pos_y = np.linspace(0, picture_size[1], image_counts[1], endpoint=False)
print(list(pos_y))

[0.0, 100.0, 200.0]
[0.0, 500.0]


In [15]:
pos = np.meshgrid(pos_x, pos_y)
pos

[array([[  0., 100., 200.],
        [  0., 100., 200.]]),
 array([[  0.,   0.,   0.],
        [500., 500., 500.]])]

In [28]:
pos[0].ravel()

array([  0., 100., 200.,   0., 100., 200.])

In [29]:
pos[1].ravel()

array([  0.,   0.,   0., 500., 500., 500.])

In [16]:
xx, yy = pos

In [17]:
xx

array([[  0., 100., 200.],
       [  0., 100., 200.]])

In [18]:
yy

array([[  0.,   0.,   0.],
       [500., 500., 500.]])

In [20]:
list(zip(xx, yy))

[(array([  0., 100., 200.]), array([0., 0., 0.])),
 (array([  0., 100., 200.]), array([500., 500., 500.]))]